# Master Snakefile

# Load configuration
configfile: "config/config.yaml"

# Global variables from config
image = config["cvmfs_apptainer_image"]
run_list = config["runs"]

# Qwpartiy input and output paths
qw_data = config["qw_data"]
qw_rootfiles = config["qw_rootfiles"]


# Internal config
#rootfile_prefix = config["rootfile_prefix"]

# Include rule files
include: "rules/processing.smk"
include: "rules/plotting.smk"

# Define the overall targets
rule all:
    input:
        # Plots are still generated within the project results directory
        expand("results/plots/bpm1i06XP_vs_bpm1i06YP_run{run}.pdf", run=run_list),
        expand("results/plots/la41_vs_la42_run{run}.pdf", run=run_list)